# Generated by Django 3.0.7 on 2023-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
