# Generated by Django 3.0.7 on 2023-06-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20230606_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
