# Generated by Django 4.2 on 2023-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("descr", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="V1Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.TextField()),
                ("sex", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("yearof", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=200)),
            ],
        ),
    ]
