# Generated by Django 4.2 on 2023-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1model",
            name="lastname",
            field=models.CharField(max_length=200),
        ),
    ]
